appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: KKxOVq/rS/h81A+dLri4GnlCDt/EcChtN+QHRkBs43GLohEhyCQKQBWfJUjaTqyC3p/kapvi5TW0j7+LF5L3OLd0qn0u3PhjuMkgWvD2kvQXDkKfgYcUUNw3gDQB/pSeUPfvoPbmdSGq4qCPsXvYOhtUxb4VeW9hx0c9pPj8x6gs7XJXkKaspU1qcsngyRobisfYBrx3G3Aa1hLqHXEM8x/BWfr3juXyuiVzqZ/96XSteKlCWRij1dcmBybxrFLRfgwiOwvNTz0bHB6YZ8DsZy2+hcIsgqeW2kGG4bfut1dzldAbFv8oSiwFSNIKrXnngnMB0Bx5jm0dNwTtBkEEZMgnab0KlhPdN6PcD7ZZVjzFAFaGU7tkO0aBVcvaZQcf/TGF3YDF78uv1UI7laasp7MU2T2ploAseuDFwNq8diLaxThnvmTfwQqO/4Cyrk88slEt0i5Lk9jIyBQFi1MtGJcCe+Aq9dGTbT01bhLAoSwZh7k7yjNCBi1ESlM5Pc+bcIGj5oRpbrcpy/is8nGqDM2FXg/n1/kRfmZYXA0hvxTbT0ko8RC7dpOSJKGIRcugbMKq7vNdfj+VZeDDS4HUOraEK3LQTxddyQltB4AiZBAm/UYOnisIxE+KmSvfoNHphx9Nma/6pkXYdcmomGqA6OtTdxudFL9di9Wt0hKNTyc=}
conda_forge_output_validation: true
